allow_cache: false
batch_max_steps: 8000
batch_size: 16
config: conf/h2emaph_gru_joint_nogan.yaml
dataset_mode: h2emaph
discriminator_adv_loss_params:
  average_by_discriminators: false
discriminator_grad_norm: -1
discriminator_optimizer_params:
  betas:
  - 0.5
  - 0.9
  lr: 0.0001
  weight_decay: 0.0
discriminator_optimizer_type: Adam
discriminator_scheduler_params:
  gamma: 0.5
  milestones:
  - 80000
  - 160000
  - 240000
  - 320000
discriminator_scheduler_type: MultiStepLR
discriminator_train_start_steps: 0
distributed: false
eval_interval_steps: 1000
exp_id: hprc_no_m1f2
feat_match_loss_params:
  average_by_discriminators: false
  average_by_layers: false
  include_final_outputs: false
fft_size: 1024
fmax: 7600
fmin: 80
format: hdf5
generator_adv_loss_params:
  average_by_discriminators: false
generator_grad_norm: -1
generator_optimizer_params:
  betas:
  - 0.5
  - 0.9
  lr: 0.0001
  weight_decay: 0.0
generator_optimizer_type: Adam
generator_params:
  dropout: 0.3
  hidden_size: 256
  in_channels: 1024
  out_channels: 53
generator_scheduler_params:
  gamma: 0.5
  milestones:
  - 80000
  - 160000
  - 240000
  - 320000
generator_scheduler_type: MultiStepLR
generator_train_start_steps: 1
generator_type: BiGRU
global_gain_scale: 1.0
hop_size: 160
lambda_adv: 0.0
lambda_aux: 45.0
lambda_feat_match: 0.0
log_interval_steps: 100
mel_loss_params:
  mode: emaph_joint
  weights:
  - 1.0
  - 0.5
num_mels: 80
num_save_intermediate_results: 4
num_workers: 2
outdir: exp/hprc_no_m1f2_h2emaph_gru_joint_nogan
pin_memory: true
pqmf: false
pretrain: ''
pretrain2: ''
rank: 0
remove_short_samples: false
resume: ''
sampling_rate: 16000
save_interval_steps: 5000
train_max_steps: 400000
trim_frame_size: 1024
trim_hop_size: 160
trim_silence: false
trim_threshold_in_db: 20
use_feat_match_loss: true
use_mel_loss: true
use_pcd: false
use_stft_loss: false
verbose: 1
version: 0.5.3
win_length: null
window: hann
